In [1]:
import numpy
Q = [
    [7,8,0,4,0,0,1,2,0],
    [6,0,0,0,7,5,0,0,9],
    [0,0,0,6,0,1,0,7,8],
    [0,0,7,0,4,0,2,6,0],
    [0,0,1,0,5,0,9,3,0],
    [9,0,4,0,6,0,0,0,5],
    [0,7,0,3,0,0,0,1,2],
    [1,2,0,0,0,7,4,0,0],
    [0,4,9,2,0,6,0,0,7]
]

In [2]:
def missing(soduck):
    l=[]
    for a in range(9):
        for b in range(9):
            if soduck[a][b]==0:
                num=[n for n in range(1,10)]
                avoid=set()
                for c in range(9):
                    avoid.add(soduck[a][c])
                    avoid.add(soduck[c][b])
                for c in range(int(b/3)*3,int(b/3)*3+3):
                    for d in range(int(a/3)*3,int(a/3)*3+3):
                        avoid.add(soduck[d][c])
                for c in avoid:
                    if c!=0:
                        num.remove(c)
                num.insert(0,0)
                l.append((a,b,num))
    return l
index=[]
def check(soduck,n,a):
    r=missing[n][0]
    w=missing[n][1]
    for b in range(9):
        if b!=r and soduck[b][w]==missing[n][2][a]:
            return False
        if b!=w and soduck[r][b]==missing[n][2][a]:
            return False
    for b in range(int(r/3)*3,int(r/3+1)*3):
        for c in range(int(w/3)*3,int(w/3+1)*3) :
            if (b,c)!=(r,w) and soduck[b][c]==missing[n][2][a]:
                return False
    return True
missing=missing(Q)

In [3]:
def solve(soduck,index):
    error=1
    if index:
        if index[-1]<10:
            n=len(index)
            index.append(0)
        else:
            del index[-1]
            n=len(index)-1
    else:
        n=0
        index.append(0)
    if n<len(missing):
        
        for a in range(index[n]+1,len(missing[n][2])):
            if check(soduck,n,a):
                index[n]=a
                soduck[missing[n][0]][missing[n][1]]=missing[n][2][index[n]]
                error=0
                break
        if error:
            index[-1]=10
            soduck[missing[n][0]][missing[n][1]]=0
        solve(soduck,index)
    else:
        import numpy
        
        print(numpy.array(soduck))
            
            

In [4]:
solve(Q,index)

[[7 8 5 4 3 9 1 2 6]
 [6 1 2 8 7 5 3 4 9]
 [4 9 3 6 2 1 5 7 8]
 [8 5 7 9 4 3 2 6 1]
 [2 6 1 7 5 8 9 3 4]
 [9 3 4 1 6 2 7 8 5]
 [5 7 8 3 9 4 6 1 2]
 [1 2 6 5 8 7 4 9 3]
 [3 4 9 2 1 6 8 5 7]]
